### PR TITLE
Remove flavors for appliances as they're currently missing

### PR DESCRIPTION
**Pull request by lkocman**
Temp workaround until https://build.opensuse.org/request/show/943798 is accepted

### CODE REVIEW

**Comment by lkocman** [comment]
Ha! interestingly they appear with 15.3 so I suppose it's just that spec was not bumped

```
lkocman@pontifex2:/home/lkocman> ls -la  /srv/ftp/pub/opensuse//distribution/leap/15.4/appliances/ | egrep -i "vmware|openstack|kvm|hyper"
-rw-r--r-- 2 mirror stage  245956608 Dec  1 12:05 openSUSE-Leap-15.3-JeOS.aarch64-15.3-kvm-Build5.1.qcow2
-rw-r--r-- 2 mirror stage        122 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.aarch64-15.3-kvm-Build5.1.qcow2.sha256
-rw-r--r-- 2 mirror stage        481 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.aarch64-15.3-kvm-Build5.1.qcow2.sha256.asc
lrwxrwxrwx 2 mirror stage         55 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.aarch64-kvm.qcow2 -> openSUSE-Leap-15.3-JeOS.aarch64-15.3-kvm-Build5.1.qcow2
-rw-r--r-- 2 mirror stage        107 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.aarch64-kvm.qcow2.sha256
-rw-r--r-- 2 mirror stage        481 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.aarch64-kvm.qcow2.sha256.asc
-rw-r--r-- 2 mirror stage  260767744 Dec  2 12:08 openSUSE-Leap-15.3-JeOS.x86_64-15.3-kvm-and-xen-Build5.1.qcow2
-rw-r--r-- 2 mirror stage        129 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.x86_64-15.3-kvm-and-xen-Build5.1.qcow2.sha256
-rw-r--r-- 2 mirror stage        481 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.x86_64-15.3-kvm-and-xen-Build5.1.qcow2.sha256.asc
-rw-r--r-- 2 mirror stage  167891364 Dec  2 12:07 openSUSE-Leap-15.3-JeOS.x86_64-15.3-MS-HyperV-Build5.1.vhdx.xz
-rw-r--r-- 2 mirror stage        129 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.x86_64-15.3-MS-HyperV-Build5.1.vhdx.xz.sha256
-rw-r--r-- 2 mirror stage        481 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.x86_64-15.3-MS-HyperV-Build5.1.vhdx.xz.sha256.asc
-rw-r--r-- 2 mirror stage  252075008 Dec  2 12:08 openSUSE-Leap-15.3-JeOS.x86_64-15.3-OpenStack-Cloud-Build5.1.qcow2
-rw-r--r-- 2 mirror stage        133 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.x86_64-15.3-OpenStack-Cloud-Build5.1.qcow2.sha256
-rw-r--r-- 2 mirror stage        481 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.x86_64-15.3-OpenStack-Cloud-Build5.1.qcow2.sha256.asc
-rw-r--r-- 2 mirror stage  168814892 Dec  2 12:08 openSUSE-Leap-15.3-JeOS.x86_64-15.3-VMware-Build5.1.vmdk.xz
-rw-r--r-- 2 mirror stage        126 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.x86_64-15.3-VMware-Build5.1.vmdk.xz.sha256
-rw-r--r-- 2 mirror stage        481 Dec  8 08:41 openSUSE-Leap-15.3-JeOS.x86_64-15.3-VMware-Build5.1.vmdk.xz.sha256.asc
-rw-r--r-- 2 mirror stage        521 Dec  2 12:08 openSUSE-Leap-15.3-JeOS.x86_64-15.3-VMware-Build5.1.vmx
lrwxrwxrwx 2 mirror stage         62 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-kvm-and-xen.qcow2 -> openSUSE-Leap-15.3-JeOS.x86_64-15.3-kvm-and-xen-Build5.1.qcow2
-rw-r--r-- 2 mirror stage        114 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-kvm-and-xen.qcow2.sha256
-rw-r--r-- 2 mirror stage        481 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-kvm-and-xen.qcow2.sha256.asc
lrwxrwxrwx 2 mirror stage         62 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-MS-HyperV.vhdx.xz -> openSUSE-Leap-15.3-JeOS.x86_64-15.3-MS-HyperV-Build5.1.vhdx.xz
-rw-r--r-- 2 mirror stage        114 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-MS-HyperV.vhdx.xz.sha256
-rw-r--r-- 2 mirror stage        481 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-MS-HyperV.vhdx.xz.sha256.asc
lrwxrwxrwx 2 mirror stage         66 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2 -> openSUSE-Leap-15.3-JeOS.x86_64-15.3-OpenStack-Cloud-Build5.1.qcow2
-rw-r--r-- 2 mirror stage        118 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256
-rw-r--r-- 2 mirror stage        481 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-OpenStack-Cloud.qcow2.sha256.asc
lrwxrwxrwx 2 mirror stage         59 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-VMware.vmdk.xz -> openSUSE-Leap-15.3-JeOS.x86_64-15.3-VMware-Build5.1.vmdk.xz
-rw-r--r-- 2 mirror stage        111 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-VMware.vmdk.xz.sha256
-rw-r--r-- 2 mirror stage        481 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-VMware.vmdk.xz.sha256.asc
lrwxrwxrwx 2 mirror stage         55 Jan  3 09:46 openSUSE-Leap-15.3-JeOS.x86_64-VMware.vmx -> openSUSE-Leap-15.3-JeOS.x86_64-15.3-VMware-Build5.1.vmx

```

**Comment by lkocman** [comment]
Waiting for fix, https://build.opensuse.org/request/show/943798

Let's keep this open until SR is accepted so I know when to remove temp workaround.

**Comment by lkocman** [comment]
No longer needed, sr merged. Closing

**Comment by Vogtinator** [comment]
Yep, it was intentionally not bumped yet because it's not ready yet, waiting for kiwi changes in SLE.

**Pull request closed without merging**
