### PR TITLE
initial copy of appliances and live config for 15.4

### PR DESCRIPTION
**Pull request by lkocman**
We should perhaps consider using -Media symlinks instead of -Current just like we've recently started to do for 15.4 base.

### CODE REVIEW

**Comment by lkocman** [comment]
ftp structure is ready

```
mirror@pontifex2:~/bin> ls -la /srv/{ftp,ftp-stage}/pub/opensuse/distribution/leap/15.4/{live,appliances}
lrwxrwxrwx 1 mirror stage 14 Dec  2 03:37 /srv/ftp/pub/opensuse/distribution/leap/15.4/live -> appliances/iso
lrwxrwxrwx 1 mirror stage 14 Dec  2 03:36 /srv/ftp-stage/pub/opensuse/distribution/leap/15.4/live -> appliances/iso

/srv/ftp/pub/opensuse/distribution/leap/15.4/appliances:
total 0
drwxr-xr-x 3 mirror stage 24 Dec  2 03:36 .
drwxr-xr-x 5 mirror stage 75 Dec  2 03:37 ..
drwxr-xr-x 2 mirror stage 10 Dec  2 03:36 iso

/srv/ftp-stage/pub/opensuse/distribution/leap/15.4/appliances:
total 0
drwxr-xr-x 3 mirror stage 24 Dec  2 03:36 .
drwxr-xr-x 6 mirror stage 96 Dec  2 03:36 ..
drwxr-xr-x 2 mirror stage 10 Dec  2 03:36 iso

```

**Comment by lkocman** [comment]
@Vogtinator ^ I did create same symlinks as in 15.3

**Comment by lkocman** [comment]
Related pr for get-o-o https://github.com/openSUSE/get-o-o/pull/65

**Comment by Vogtinator** [comment]
Thanks! The symlinks are mostly for compatibility (software-o-o and get-o-o), so technically they shouldn't be needed anymore. Won't hurt though. It looks like currently get-o-o still uses the old location.

**Pull request merged**
